"""R5a step 6: `botcorp tools <bot> scan | register | retire` (cli/tools.mjs).

Fixture tree: one automation-referenced script, one rule-referenced script,
two modules only imported by it (one directory), one orphan, one sync shim and
one `_private.py`. The scan proposes exactly two exact entries, one lib glob
and one orphan; the shim and the private module are not executables at all.
register --file applies a non-widening proposal even from a bot; retire moves
the file under <rt>/retired/<bot>/<stamp>/ and appends one retired.jsonl line.
"""
from __future__ import annotations

import json

import pytest

from test_operator_only import box, cli, needs_node  # noqa: F401

SHIM_MARKER = "# botcorp-shim: generated by botcorp sync"

YAML = (
    "name: t\nharness:\n  service: manual\n"
    "automations:\n"
    "  - name: mon\n    command: python tools/mon/watch.py --once\n    trigger: { interval_min: 10 }\n"
)


@pytest.fixture
def tree(box):
    rt, bots, env = box
    home = bots / "t"
    (home / "bot.yaml").write_text(YAML, encoding="utf-8")
    files = {
        "tools/mon/watch.py": "print('watch')\n",
        "tools/cli/report.py": "from helpers import fmt\nimport util2\n",
        "tools/lib/helpers.py": "def fmt(x):\n    return x\n",
        "tools/lib/util2.py": "X = 1\n",
        "tools/lib/_private.py": "Y = 2\n",
        "tools/old/dead.py": "print('nobody calls me')\n",
        "tools/v2/shimmed.py": f"{SHIM_MARKER}\nREL = \"v2/shimmed.py\"\n",
        ".claude/rules/tools.md": "Run `python tools/cli/report.py` for the weekly report.\n",
    }
    for rel, text in files.items():
        f = home / rel
        f.parent.mkdir(parents=True, exist_ok=True)
        f.write_text(text, encoding="utf-8")
    return rt, bots, env, home


@needs_node
def test_scan_classifies_the_fixture_tree(tree):
    rt, bots, env, home = tree
    r = cli(env, "tools", "t", "scan", "--json", "--proposal", str(rt / "p.yaml"))
    assert r.returncode == 0, r.stderr
    d = json.loads(r.stdout)
    assert d["registry"] == "off"
    assert "tools/v2/shimmed.py" not in d["executables"] and "tools/lib/_private.py" not in d["executables"]
    tools = {e["path"]: e for e in d["proposal"]["tools"]}
    assert set(tools) == {"tools/mon/watch.py", "tools/cli/report.py", "tools/lib/*.py"}
    assert tools["tools/mon/watch.py"]["kind"] == "monitor"
    assert tools["tools/cli/report.py"]["kind"] == "cli"
    assert tools["tools/lib/*.py"]["kind"] == "lib"
    assert d["proposal"]["orphans"] == ["tools/old/dead.py"]
    assert (rt / "p.yaml").exists()


@needs_node
def test_register_file_from_a_bot_applies_a_plain_proposal(tree):
    rt, bots, env, home = tree
    assert cli(env, "tools", "t", "scan", "--proposal", str(rt / "p.yaml")).returncode == 0
    r = cli({**env, "BOT_NAME": "t"}, "tools", "t", "register", "--file", str(rt / "p.yaml"))
    assert r.returncode == 0 and "applied" in r.stdout, r.stdout + r.stderr
    d = json.loads(cli(env, "tools", "t", "scan", "--json").stdout)
    assert d["registry"] == "warn" and len(d["registered"]) == 3
    assert d["unregistered"] == ["tools/old/dead.py"] and d["missing"] == []
    # registering the same file again is a no-op
    r = cli(env, "tools", "t", "register", "--file", str(rt / "p.yaml"))
    assert r.returncode == 0 and "nothing new" in r.stdout


@needs_node
def test_register_an_integration_from_a_bot_queues(tree):
    rt, bots, env, home = tree
    before = (home / "bot.yaml").read_text(encoding="utf-8")
    r = cli({**env, "BOT_NAME": "t"}, "tools", "t", "register", "--name", "rep", "--path", "tools/cli/report.py", "--kind", "integration")
    assert r.returncode == 0 and "queued" in r.stdout, r.stdout + r.stderr
    assert (home / "bot.yaml").read_text(encoding="utf-8") == before
    r = cli(env, "tools", "t", "register", "--name", "rep", "--path", "tools/cli/report.py", "--kind", "integration")
    assert r.returncode == 0 and "applied" in r.stdout, r.stdout + r.stderr


@needs_node
def test_retire_moves_the_orphan_and_logs_one_line(tree):
    rt, bots, env, home = tree
    r = cli({**env, "BOT_NAME": "t"}, "tools", "t", "retire", "tools/old/dead.py")
    assert r.returncode == 0, r.stdout + r.stderr
    assert not (home / "tools" / "old" / "dead.py").exists()
    moved = list((rt / "retired" / "t").glob("*/tools/old/dead.py"))
    assert len(moved) == 1
    lines = (rt / "retired" / "t" / "retired.jsonl").read_text(encoding="utf-8").splitlines()
    assert len(lines) == 1 and json.loads(lines[0])["files"] == ["tools/old/dead.py"]


@needs_node
def test_retire_refuses_a_path_outside_the_tools(tree):
    rt, bots, env, home = tree
    r = cli(env, "tools", "t", "retire", "../../etc/passwd")
    assert r.returncode == 1
    r = cli(env, "tools", "t", "retire", "bot.yaml")
    assert r.returncode == 1 and (home / "bot.yaml").exists()
