"""v0.1.11: every harness tool a bot is told to run resolves from its folder.

v0.1.10 shimmed tools/tg only. The rules, skills, agents, hooks' nudges and
the bot template's CLAUDE.md also say `python tools/v2/recall.py`, `bash
tools/browser/ab.sh`, `tools/infra/sanitize.py`, ... relative to the bot
folder, where none of them exist.

Locked behaviour:
- sync shims every tool (.py, .sh, .ps1; not `_`-prefixed modules) of every
  harness tools/<dir>/, so a new tool or folder needs no code change;
- EVERY relative `tools/<dir>/<file>` reference anywhere in the harness or the
  bot template resolves in a synced bot folder to a shim of an existing
  harness file; the only exception is a reference in a file that declares the
  tool is the bot's own ("the harness ships no `tools/<dir>/`");
- the .sh shim execs the harness copy with "$@" (args, stdin, exit code), the
  .ps1 shim passes @args and the exit code;
- a .py shim IMPORTED by a bot's own script is the harness module (its CLI
  does not run);
- a shim left in a folder the harness no longer has is removed;
- toolShimsVerdictOf (doctor `<bot>: harness tools reachable`).
"""
from __future__ import annotations

import json
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

import pytest

ASSEMBLY = Path(__file__).resolve().parents[2]
SYNC = ASSEMBLY / "daemon" / "sync.mjs"
LIB = (ASSEMBLY / "cli" / "_lib.mjs").as_uri()
MARKER = "# botcorp-shim: generated by botcorp sync"

pytestmark = pytest.mark.skipif(shutil.which("node") is None, reason="node not on PATH")

# A relative reference: not preceded by a path character, so `$HARNESS/tools/...`
# and `harness/tools/...` (absolute, fine as they are) do not count.
REF_RE = re.compile(r"(?<![\w/$.~-])tools/([\w-]+)/([\w-]+\.(?:py|sh|ps1|cjs|mjs|js))\b")
TEXT_EXTS = {".md", ".sh", ".py", ".json", ".txt", ".yaml", ".yml", ".ps1", ".cjs", ".mjs", ".js"}
YAML = "name: beta\nharness:\n  modules:\n    telegram: true\nintegrations:\n  telegram:\n    allow_from: [123456]\n"


def _root(tmp_path: Path, extra_tools: dict | None = None) -> Path:
    root = tmp_path / "root"
    shutil.copytree(ASSEMBLY / "templates", root / "templates")
    shutil.copytree(ASSEMBLY / "harness" / "tools", root / "harness" / "tools", ignore=shutil.ignore_patterns("__pycache__"))
    for rel, text in (extra_tools or {}).items():
        f = root / "harness" / "tools" / rel
        f.parent.mkdir(parents=True, exist_ok=True)
        f.write_text(text, encoding="utf-8")
    home = root / "bots" / "beta"
    home.mkdir(parents=True)
    (home / "bot.yaml").write_text(YAML, encoding="utf-8")
    return root


def _sync(root: Path) -> subprocess.CompletedProcess:
    r = subprocess.run(["node", str(SYNC), "beta", "--botcorp", str(root)], capture_output=True, text=True, timeout=60)
    assert r.returncode == 0, r.stderr
    return r


def _refs() -> dict[str, set[str]]:
    """relative tools/<dir>/<file> reference -> the harness/template files that make it"""
    out: dict[str, set[str]] = {}
    for base in (ASSEMBLY / "harness", ASSEMBLY / "templates" / "bot"):
        for f in base.rglob("*"):
            if not f.is_file() or f.suffix not in TEXT_EXTS or "__pycache__" in f.parts or "tests" in f.relative_to(ASSEMBLY / "harness" if base.name == "harness" else base).parts[:1]:
                continue
            for m in REF_RE.finditer(f.read_text(encoding="utf-8", errors="replace")):
                out.setdefault(f"tools/{m.group(1)}/{m.group(2)}", set()).add(f.relative_to(ASSEMBLY).as_posix())
    return out


def test_every_relative_tool_reference_resolves_from_a_synced_bot_folder(tmp_path):
    refs = _refs()
    # positive control + floor: the scan sees the references this release is about
    for known in ("tools/tg/tg_send.py", "tools/v2/recall.py", "tools/browser/ab.sh", "tools/infra/sanitize.py", "tools/infra/resource_monitor.ps1"):
        assert known in refs, f"scanner missed {known}"
    assert len(refs) >= 25, sorted(refs)
    root = _root(tmp_path)
    _sync(root)
    home = root / "bots" / "beta"
    unresolved = []
    for ref, where in sorted(refs.items()):
        dir_ = ref.split("/")[1]
        declared = all(f"the harness ships no `tools/{dir_}/`" in (ASSEMBLY / w).read_text(encoding="utf-8") for w in where)
        shim = home / ref
        if shim.is_file() and MARKER in shim.read_text(encoding="utf-8").splitlines()[:2] and (root / "harness" / ref).is_file():
            continue
        if declared and not (ASSEMBLY / "harness" / ref).exists():
            continue   # the bot's own tool, and every file that names it says so
        unresolved.append(f"{ref} (from {', '.join(sorted(where))})")
    assert not unresolved, "relative tool references with no shim:\n  " + "\n  ".join(unresolved)


def test_sync_shims_every_harness_tool_folder_and_skips_private_modules(tmp_path):
    root = _root(tmp_path)
    r = _sync(root)
    home = root / "bots" / "beta" / "tools"
    for d in ("tg", "v2", "infra", "browser"):
        src = sorted(p.name for p in (root / "harness" / "tools" / d).iterdir() if p.suffix in (".py", ".sh", ".ps1") and not p.name.startswith("_"))
        assert src and sorted(p.name for p in (home / d).iterdir()) == src, d
    assert not (home / "v2" / "__init__.py").exists() and not (home / "v2" / "_session.py").exists()
    assert (home / "browser" / "ab.sh").read_text(encoding="utf-8").startswith("#!/usr/bin/env bash\n" + MARKER + "\n")
    assert (home / "infra" / "resource_monitor.ps1").read_text(encoding="utf-8").startswith(MARKER + "\n")
    assert re.search(r"^created\s+tools/v2/recall\.py$", r.stdout, re.M)


def test_a_shim_in_a_folder_the_harness_dropped_is_removed(tmp_path):
    root = _root(tmp_path, {"gone/old.py": "print('x')\n"})
    _sync(root)
    shim = root / "bots" / "beta" / "tools" / "gone" / "old.py"
    own = root / "bots" / "beta" / "tools" / "gone" / "mine.py"
    own.write_text("print('mine')\n", encoding="utf-8")
    assert shim.is_file()
    shutil.rmtree(root / "harness" / "tools" / "gone")
    r = _sync(root)
    assert not shim.exists() and own.is_file()
    assert "removed (harness tool gone) tools/gone/old.py" in r.stdout


@pytest.mark.skipif(shutil.which("bash") is None, reason="bash not on PATH")
def test_the_bash_shim_execs_the_harness_copy_with_args_stdin_and_exit_code(tmp_path):
    root = _root(tmp_path, {"fake/echo.sh": 'printf "arg:%s\\n" "$@"\nread -r line; echo "stdin:$line"\necho "from:${BASH_SOURCE[0]}"\nexit 7\n'})
    _sync(root)
    r = subprocess.run(["bash", "tools/fake/echo.sh", "a b", "--flag"], cwd=str(root / "bots" / "beta"), input="hello\n",
                       capture_output=True, text=True, timeout=60)
    assert r.returncode == 7, r.stderr
    assert "arg:a b\narg:--flag\nstdin:hello\n" in r.stdout
    assert "harness/tools/fake/echo.sh" in r.stdout.replace("\\", "/")


@pytest.mark.skipif(shutil.which("pwsh") is None, reason="pwsh not on PATH")
def test_the_powershell_shim_passes_args_and_the_exit_code(tmp_path):
    root = _root(tmp_path, {"fake/echo.ps1": 'param([switch]$Clean, [string]$Name)\n"clean=$Clean name=$Name from=$PSCommandPath"\nexit 5\n'})
    _sync(root)
    r = subprocess.run(["pwsh", "-NoProfile", "-NonInteractive", "-File", os.path.join("tools", "fake", "echo.ps1"), "-Clean", "-Name", "x y"],
                       cwd=str(root / "bots" / "beta"), capture_output=True, text=True, timeout=120)
    assert r.returncode == 5, r.stderr + r.stdout
    assert "clean=True name=x y" in r.stdout
    assert "harness" in r.stdout and "fake" in r.stdout


def test_a_python_shim_imported_by_a_bots_own_script_is_the_harness_module(tmp_path):
    root = _root(tmp_path, {"fake/lib_mod.py": 'VALUE = 42\nif __name__ == "__main__":\n    print("CLI RAN")\n'})
    _sync(root)
    home = root / "bots" / "beta"
    (home / "tools" / "fake" / "user.py").write_text("import lib_mod\nprint(lib_mod.VALUE, lib_mod.__file__)\n", encoding="utf-8")
    r = subprocess.run([sys.executable, os.path.join("tools", "fake", "user.py")], cwd=str(home), capture_output=True, text=True, timeout=60)
    assert r.returncode == 0, r.stderr
    assert "CLI RAN" not in r.stdout
    value, file = r.stdout.split(" ", 1)
    assert value == "42" and Path(file.strip()) == (root / "harness" / "tools" / "fake" / "lib_mod.py").resolve()
    run = subprocess.run([sys.executable, os.path.join("tools", "fake", "lib_mod.py")], cwd=str(home), capture_output=True, text=True, timeout=60)
    assert run.returncode == 0 and "CLI RAN" in run.stdout


def _verdict(arg: dict) -> dict:
    script = f"const m = await import({json.dumps(LIB)}); console.log(JSON.stringify(m.toolShimsVerdictOf({json.dumps(arg)})));"
    r = subprocess.run(["node", "--input-type=module", "-e", script], capture_output=True, text=True, timeout=60, cwd=str(ASSEMBLY))
    assert r.returncode == 0, r.stderr
    return json.loads(r.stdout.strip().splitlines()[-1])


def test_doctor_harness_tools_verdict():
    rows = [{"rel": "tools/v2/recall.py", "kind": "shim"}, {"rel": "tools/browser/ab.sh", "kind": "own"}]
    ok = _verdict({"rows": rows})
    assert ok["level"] == "PASS" and "2 tools (1 shims, 1 bot-owned)" in ok["detail"]
    bad = _verdict({"rows": rows + [{"rel": "tools/v2/journal.py", "kind": "missing"}]})
    assert bad["level"] == "FAIL" and "tools/v2/journal.py missing" in bad["detail"] and "botcorp sync <bot>" in bad["detail"]
    assert _verdict({"rows": rows + [{"rel": "tools/x/y.py", "kind": "stale"}]})["level"] == "FAIL"
    assert _verdict({"rows": rows, "outdated": ["tools/v2/recall.py"]})["level"] == "WARN"
    many = _verdict({"rows": [{"rel": f"tools/v2/t{i}.py", "kind": "missing"} for i in range(9)]})
    assert "(+3 more)" in many["detail"]
