"""v0.1.10: a bot's relative `python tools/tg/*.py` calls reach the harness.

Reference host: the bot's CLAUDE.md and rules said `python tools/tg/tg_send.py`
(relative to the bot folder), but the tool ships at harness/tools/tg/, so the
call failed and the bot fell back to a plaintext plugin reply. The media
senders also only read their token and chat from <bot>/.env, and nothing
wired bot.yaml integrations.telegram.chat_id to any of them.

Locked behaviour:
- sync writes a forwarding shim per harness tools/tg/*.py into bots/<bot>/tools/tg/,
  idempotently; a bot's own copy is never touched; a shim whose harness tool
  is gone is removed;
- a relative call from the bot folder runs the HARNESS file (argv, stdin and
  the exit code pass through), also when the shim sits outside a BotCorp tree
  (the checkout baked in at sync);
- the default chat: env > <bot>/.env > bot.yaml chat_id (telegram.json) > the
  only allowFrom id; several ids and no chat_id = no default;
- the media senders resolve the same way and honour BOT_TG_MUTE;
- tgToolsVerdictOf (doctor `<bot>: tg tools reachable`).
No network anywhere: sends run under BOT_TG_MUTE=1, the rest is --check.
"""
from __future__ import annotations

import json
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

import pytest

ASSEMBLY = Path(__file__).resolve().parents[2]
SYNC = ASSEMBLY / "daemon" / "sync.mjs"
LIB = (ASSEMBLY / "cli" / "_lib.mjs").as_uri()

pytestmark = pytest.mark.skipif(shutil.which("node") is None, reason="node not on PATH")

DUMMY_TOKEN = "dummy-telegram-for-tests-only-Q7w3"


def _root(tmp_path: Path, yaml_text: str, name: str = "beta") -> Path:
    root = tmp_path / "root"
    shutil.copytree(ASSEMBLY / "templates", root / "templates")
    tools = root / "harness" / "tools"
    shutil.copytree(ASSEMBLY / "harness" / "tools" / "tg", tools / "tg", ignore=shutil.ignore_patterns("__pycache__"))
    shutil.copy2(ASSEMBLY / "harness" / "tools" / "_paths.py", tools / "_paths.py")
    home = root / "bots" / name
    home.mkdir(parents=True)
    (home / "bot.yaml").write_text(yaml_text, encoding="utf-8")
    return root


def _sync(root: Path, name: str = "beta") -> subprocess.CompletedProcess:
    r = subprocess.run(["node", str(SYNC), name, "--botcorp", str(root)], capture_output=True, text=True, timeout=60)
    assert r.returncode == 0, r.stderr
    return r


def _env(root: Path, name: str = "beta", **extra: str) -> dict:
    env = {k: v for k, v in os.environ.items() if not k.startswith(("TELEGRAM_", "BOT_", "CLAUDE_"))}
    home = root / "bots" / name
    env.update({"BOT_HOME": str(home), "BOT_NAME": name, "CLAUDE_CONFIG_DIR": str(home / f".claude-{name}"),
                "BOTCORP_HOME": str(root / "rt"), "PYTHONIOENCODING": "utf-8", "BOT_TG_STATUS": "0"})
    env.update(extra)
    return env


def _py(root: Path, args: list, name: str = "beta", cwd: Path | None = None, **extra: str) -> subprocess.CompletedProcess:
    return subprocess.run([sys.executable, *args], cwd=str(cwd or root / "bots" / name), env=_env(root, name, **extra),
                          capture_output=True, text=True, timeout=60, encoding="utf-8")


def _check(r: subprocess.CompletedProcess) -> dict:
    assert r.returncode == 0, r.stderr + r.stdout
    return dict(ln.split(": ", 1) for ln in r.stdout.splitlines() if ": " in ln)


TG_YAML = "name: beta\nharness:\n  modules:\n    telegram: true\nintegrations:\n  telegram:\n    allow_from: [123456]\n"


def test_sync_writes_one_shim_per_harness_tool_and_is_idempotent(tmp_path):
    root = _root(tmp_path, TG_YAML)
    r = _sync(root)
    shims = root / "bots" / "beta" / "tools" / "tg"
    harness = sorted(p.name for p in (root / "harness" / "tools" / "tg").glob("*.py"))
    assert "tg_send.py" in harness and "tg_send_photo.py" in harness
    assert sorted(p.name for p in shims.glob("*.py")) == harness
    for n in harness:
        assert (shims / n).read_text(encoding="utf-8").startswith("# botcorp-shim: generated by botcorp sync\n")
        assert re.search(rf"^created\s+tools/tg/{re.escape(n)}$", r.stdout, re.M)
    r2 = _sync(root)
    assert "tools/tg/" not in r2.stdout
    assert re.search(rf"^unchanged\s+tools/ shims \({len(harness)}\)$", r2.stdout, re.M)


def test_sync_never_touches_a_bots_own_copy_and_removes_orphan_shims(tmp_path):
    root = _root(tmp_path, TG_YAML)
    shims = root / "bots" / "beta" / "tools" / "tg"
    shims.mkdir(parents=True)
    own = "print('the bot wrote this one')\n"
    (shims / "tg_history.py").write_text(own, encoding="utf-8")
    (shims / "my_tool.py").write_text(own, encoding="utf-8")
    _sync(root)
    orphan = shims / "tg_gone.py"
    orphan.write_text((shims / "tg_send.py").read_text(encoding="utf-8").replace("tg_send.py", "tg_gone.py"), encoding="utf-8")
    r = _sync(root)
    assert (shims / "tg_history.py").read_text(encoding="utf-8") == own
    assert (shims / "my_tool.py").read_text(encoding="utf-8") == own
    assert "kept (bot-owned) tools/tg/tg_history.py" in r.stdout
    assert not orphan.exists() and "removed (harness tool gone) tools/tg/tg_gone.py" in r.stdout


def test_a_relative_call_from_the_bot_folder_runs_the_harness_tool(tmp_path):
    root = _root(tmp_path, TG_YAML)
    _sync(root)
    c = _check(_py(root, [os.path.join("tools", "tg", "tg_send.py"), "--check"], TELEGRAM_BOT_TOKEN=DUMMY_TOKEN))
    assert Path(c["harness"]) == (root / "harness" / "tools" / "tg" / "tg_send.py").resolve()
    assert c["token"] == "...Q7w3 (env TELEGRAM_BOT_TOKEN)"
    assert DUMMY_TOKEN not in json.dumps(c)
    assert c["chat"] == "123456 (the only allowFrom id in access.json)"


def test_a_relative_send_is_muted_and_the_exit_code_passes_through(tmp_path):
    root = _root(tmp_path, TG_YAML)
    _sync(root)
    sent = _py(root, [os.path.join("tools", "tg", "tg_send.py"), "hello from the shim"], TELEGRAM_BOT_TOKEN=DUMMY_TOKEN, BOT_TG_MUTE="1")
    assert sent.returncode == 0, sent.stderr
    assert "[BOT_TG_MUTE] suppressed TG send:\nhello from the shim" in sent.stderr
    # stdin reaches the harness tool too
    piped = subprocess.run([sys.executable, os.path.join("tools", "tg", "tg_send.py")], input="piped text", cwd=str(root / "bots" / "beta"),
                           env=_env(root, TELEGRAM_BOT_TOKEN=DUMMY_TOKEN, BOT_TG_MUTE="1"), capture_output=True, text=True, timeout=60, encoding="utf-8")
    assert piped.returncode == 0 and "piped text" in piped.stderr
    empty = _py(root, [os.path.join("tools", "tg", "tg_send.py"), " "], BOT_TG_MUTE="1")
    assert empty.returncode == 1 and "empty text" in empty.stderr


def test_media_senders_reach_the_harness_resolve_like_tg_send_and_honour_mute(tmp_path):
    root = _root(tmp_path, TG_YAML)
    _sync(root)
    pic = tmp_path / "pic.png"
    pic.write_bytes(b"\x89PNG\r\n\x1a\n")
    for tool, kind in (("tg_send_photo.py", "photo"), ("tg_send_document.py", "document"), ("tg_send_video.py", "video")):
        r = _py(root, [os.path.join("tools", "tg", tool), str(pic), "caption"], TELEGRAM_BOT_TOKEN=DUMMY_TOKEN, BOT_TG_MUTE="1")
        assert r.returncode == 0, r.stderr
        assert f"[BOT_TG_MUTE] suppressed TG {kind}: pic.png" in r.stderr
    # no .env and several allowlisted ids: the chat error names the fix instead of ".env"
    access = root / "bots" / "beta" / ".claude-beta" / "channels" / "telegram" / "access.json"
    j = json.loads(access.read_text(encoding="utf-8"))
    j["allowFrom"] = ["123456", "654321"]
    access.write_text(json.dumps(j), encoding="utf-8")
    r = _py(root, [os.path.join("tools", "tg", "tg_send_photo.py"), str(pic)], TELEGRAM_BOT_TOKEN=DUMMY_TOKEN)
    assert r.returncode == 1 and "integrations.telegram.chat_id" in r.stderr


def test_default_chat_resolution_order(tmp_path):
    root = _root(tmp_path, TG_YAML.replace("allow_from: [123456]", "allow_from: [123456, 654321]"))
    _sync(root)
    send = [os.path.join("tools", "tg", "tg_send.py"), "--check"]
    assert _check(_py(root, send))["chat"].startswith("none - no default chat: pass --chat-id, or set integrations.telegram.chat_id")
    (root / "bots" / "beta" / "bot.yaml").write_text(TG_YAML.replace("allow_from: [123456]", "allow_from: [123456, 654321]\n    chat_id: 654321"), encoding="utf-8")
    _sync(root)
    gen = json.loads((root / "bots" / "beta" / ".claude-beta" / "botcorp" / "telegram.json").read_text(encoding="utf-8"))
    assert gen["default_chat_id"] == "654321"
    assert _check(_py(root, send))["chat"] == "654321 (bot.yaml integrations.telegram.chat_id)"
    (root / "bots" / "beta" / ".env").write_text("TELEGRAM_CHAT_ID=111\n", encoding="utf-8")
    assert _check(_py(root, send))["chat"] == "111 (<bot>/.env)"
    assert _check(_py(root, send, TELEGRAM_CHAT_ID="222"))["chat"] == "222 (env TELEGRAM_CHAT_ID)"


def test_a_shim_outside_a_botcorp_tree_uses_the_checkout_sync_baked_in(tmp_path):
    root = _root(tmp_path, TG_YAML)
    _sync(root)
    away = tmp_path / "away"
    away.mkdir()
    shutil.copy2(root / "bots" / "beta" / "tools" / "tg" / "tg_send.py", away / "tg_send.py")
    c = _check(_py(root, [str(away / "tg_send.py"), "--check"], cwd=away))
    assert Path(c["harness"]) == (root / "harness" / "tools" / "tg" / "tg_send.py").resolve()
    shutil.rmtree(root / "harness")
    gone = _py(root, [str(away / "tg_send.py"), "--check"], cwd=away)
    assert gone.returncode == 1 and "botcorp shim: harness tool not found" in gone.stderr and "botcorp sync" in gone.stderr


def _verdict(arg: dict) -> dict:
    script = f"const m = await import({json.dumps(LIB)}); console.log(JSON.stringify(m.tgToolsVerdictOf({json.dumps(arg)})));"
    r = subprocess.run(["node", "--input-type=module", "-e", script], capture_output=True, text=True, timeout=60, cwd=str(ASSEMBLY))
    assert r.returncode == 0, r.stderr
    return json.loads(r.stdout.strip().splitlines()[-1])


def test_doctor_tg_tools_verdict():
    rows = [{"rel": "tools/tg/tg_send.py", "kind": "shim"}, {"rel": "tools/tg/tg_log.py", "kind": "own"}]
    ok = {"code": 0, "out": "harness: /b/harness/tools/tg/tg_send.py\ntoken: none\nchat: 123 (the only allowFrom id in access.json)\n", "err": ""}
    v = _verdict({"rows": rows, "probe": ok})
    assert v["level"] == "PASS" and "2 tools (1 shims, 1 bot-owned)" in v["detail"] and "default chat 123" in v["detail"]
    missing = _verdict({"rows": rows + [{"rel": "tools/tg/tg_send_photo.py", "kind": "missing"}], "probe": ok})
    assert missing["level"] == "FAIL" and "tools/tg/tg_send_photo.py missing" in missing["detail"] and "botcorp sync <bot>" in missing["detail"]
    stale = _verdict({"rows": rows + [{"rel": "tools/tg/old.py", "kind": "stale"}], "probe": ok})
    assert stale["level"] == "FAIL"
    broke = _verdict({"rows": rows, "probe": {"code": 1, "out": "", "err": "botcorp shim: harness tool not found (tried x): run botcorp sync <bot>"}})
    assert broke["level"] == "FAIL" and "harness tool not found" in broke["detail"]
    nochat = _verdict({"rows": rows, "probe": {**ok, "out": "harness: /b/x.py\ntoken: none\nchat: none - no default chat\n"}})
    assert nochat["level"] == "WARN"
    assert _verdict({"rows": rows, "outdated": ["tools/tg/tg_send.py"], "probe": ok})["level"] == "WARN"
    assert _verdict({"rows": rows, "probe": None})["level"] == "WARN"
    assert _verdict({"rows": [], "probe": ok})["level"] == "FAIL"
