#!/usr/bin/env bash
# PreToolUse guard (Edit|Write|MultiEdit|NotebookEdit) — block direct writes to
# harness-managed config the bot must not self-modify: bot.yaml, generated
# settings.json, the secrets vault, and the Telegram access allowlist.
#
# FAIL-CLOSED for the files it names (exit 2 blocks the tool call and feeds
# the message back to the model); everything else is a silent exit 0.

set -uo pipefail
. "$(dirname "$0")/_guard.sh" config-guard

PAYLOAD=""
if ! [ -t 0 ]; then
  PAYLOAD=$(cat || true)
fi
[ -n "$PAYLOAD" ] || exit 0

FILE=$("$PY" -c "
import json, sys
try:
    d = json.loads(sys.stdin.read() or '{}')
    ti = d.get('tool_input') or {}
    print(ti.get('file_path') or ti.get('notebook_path') or '')
except Exception:
    pass
" <<<"$PAYLOAD" 2>/dev/null) || exit 0
[ -n "$FILE" ] || exit 0

# Normalise backslashes to forward slashes and lowercase for a
# case-insensitive, separator-insensitive comparison (Windows paths).
FILE_N=$(printf '%s' "$FILE" | tr '\\' '/' | tr '[:upper:]' '[:lower:]')
BOT_HOME_N=$(printf '%s' "$BOT_HOME" | tr '\\' '/' | tr '[:upper:]' '[:lower:]')

CONFIG_HOME="${CLAUDE_CONFIG_DIR:-$HOME/.claude}"
CONFIG_HOME_N=$(printf '%s' "$CONFIG_HOME" | tr '\\' '/' | tr '[:upper:]' '[:lower:]')

BLOCKED=0
case "$FILE_N" in
  "$BOT_HOME_N/bot.yaml") BLOCKED=1 ;;
  "$BOT_HOME_N/.claude/settings.json") BLOCKED=1 ;;
  "$BOT_HOME_N/.vault/"*) BLOCKED=1 ;;
  "$CONFIG_HOME_N/channels/telegram/access.json") BLOCKED=1 ;;
esac

[ "$BLOCKED" = "1" ] || exit 0

echo "BLOCKED: $FILE is harness-managed. Use \`botcorp config set <bot> <path> <value>\` for bot.yaml (widening changes need operator approval in the cockpit), \`botcorp secrets set\` for the vault, the cockpit pairing panel for access.json; settings.json is generated by \`botcorp sync\` — edit bot.yaml or settings.local.json instead." >&2
exit 2
