// Chat view - render a bot's live Claude Code session as clean chat turns.
//
// BEST-EFFORT ONLY. This reads Claude Code's session transcript
// (<config home>/projects/<slug>/<session>.jsonl). That format is internal
// and may change between Claude Code versions; nothing else in BotCorp
// depends on this module, every entry point is wrapped, and a failure
// degrades to { available: false } so the terminal view still works. The
// compose box does not go through here: it writes keystrokes to the pty.

import { promises as fs } from 'node:fs';
import path from 'node:path';
import { ccProjectSlug } from './bots.mjs';

// Locate the bot's ACTIVE transcript: newest .jsonl under projects/, preferring
// the dir whose slug is the bot's own BOT_HOME. null when there is none yet.
async function currentTranscript(bot) {
  const projectsDir = path.join(bot.configDir, 'projects');
  let dirs;
  try { dirs = await fs.readdir(projectsDir, { withFileTypes: true }); } catch { return null; }
  const ownSlug = ccProjectSlug(bot.home).toLowerCase();
  let best = null;
  for (const d of dirs) {
    if (!d.isDirectory()) continue;
    const own = d.name.toLowerCase() === ownSlug;
    const dir = path.join(projectsDir, d.name);
    let files;
    try { files = await fs.readdir(dir); } catch { continue; }
    for (const f of files) {
      if (!f.endsWith('.jsonl')) continue;
      let st;
      try { st = await fs.stat(path.join(dir, f)); } catch { continue; }
      const cand = { file: path.join(dir, f), mtime: st.mtimeMs, own };
      if (!best) { best = cand; continue; }
      if (cand.own && !best.own) { best = cand; continue; }
      if (cand.own === best.own && cand.mtime > best.mtime) best = cand;
    }
  }
  return best ? best.file : null;
}

function textFromContent(content) {
  if (typeof content === 'string') return content;
  if (Array.isArray(content)) return content.filter((p) => p?.type === 'text').map((p) => p.text || '').join('\n');
  return '';
}

function toolsFromContent(content) {
  if (!Array.isArray(content)) return [];
  return content.filter((p) => p?.type === 'tool_use').map((p) => p.name).filter(Boolean);
}

// Claude Code injects synthetic "user" entries that nobody typed: slash-command
// wrappers, their captured output, bash-mode carriers and the "Caveat:" preamble.
const META_USER_PREFIXES = [
  '<command-name>', '<command-message>', '<command-args>',
  '<local-command-stdout>', '<local-command-stderr>',
  '<bash-input>', '<bash-stdout>', '<bash-stderr>',
  '<task-notification>', '<system-reminder>',
  'Caveat: The messages below were generated by the user while running local commands',
];

// Inbound channel messages (Telegram and any other `source=`) arrive as
//   <channel source="plugin:telegram:telegram" chat_id=".." user=".." ts="..">body</channel>
// possibly several per entry, with surrounding text. Returned as body text plus
// a small meta line; media attributes become a marker, never a filesystem path.
const CHANNEL_RE = /<channel\b([^>]*)>([\s\S]*?)<\/channel>/g;
const ATTR_RE = /([a-zA-Z_][\w-]*)\s*=\s*"([^"]*)"/g;
function sourceLabel(src) {
  const last = String(src || '').split(':').filter(Boolean).pop() || '';
  return last ? last.charAt(0).toUpperCase() + last.slice(1) : 'Channel';
}
export function parseChannelText(text) {
  const blocks = [];
  let rest = '';
  let at = 0;
  for (const m of String(text || '').matchAll(CHANNEL_RE)) {
    rest += text.slice(at, m.index);
    at = m.index + m[0].length;
    const attrs = {};
    for (const a of m[1].matchAll(ATTR_RE)) attrs[a[1]] = a[2];
    const media = [];
    if (attrs.image_path) media.push('image');
    if (attrs.attachment_file_id || attrs.attachment_name) media.push(attrs.attachment_name ? String(attrs.attachment_name).replace(/^.*[\\/]/, '').slice(0, 80) : (attrs.attachment_kind || 'file'));
    blocks.push({ body: m[2].trim(), source: sourceLabel(attrs.source), user: attrs.user || null, ts: attrs.ts || null, media });
  }
  if (!blocks.length) return null;
  rest = (rest + text.slice(at)).trim();
  const first = blocks[0];
  const body = [rest, ...blocks.map((b) => b.body)].filter(Boolean).join('\n\n');
  return { text: body, meta: { source: first.source, user: first.user, ts: first.ts, media: blocks.flatMap((b) => b.media) } };
}
// Background agents and commands report back as a synthetic user entry:
//   <task-notification><task-id>..</task-id><output-file>..</output-file>
//   <status>completed</status><summary>..</summary><result>..</result>
//   <usage><total_tokens>N</total_tokens><tool_uses>N</tool_uses><duration_ms>N</duration_ms></usage>
// A system event, not something anyone typed: one card per block, carrying only
// summary, status, usage and result (never the output-file path or ids).
const TASK_RE = /<task-notification>([\s\S]*?)<\/task-notification>/g;
const RESULT_MAX = 20000;
function tagText(block, name) {
  const open = block.indexOf(`<${name}>`);
  if (open < 0) return '';
  const from = open + name.length + 2;
  // the result is free text that may quote a closing tag: take the last one
  const close = name === 'result' ? block.lastIndexOf(`</${name}>`) : block.indexOf(`</${name}>`, from);
  return close < from ? '' : block.slice(from, close).trim();
}
export function parseTaskNotifications(text) {
  const cards = [];
  for (const m of String(text || '').matchAll(TASK_RE)) {
    const block = m[1];
    const usage = {};
    // <usage> is child tags or `key: value` lines, depending on the Claude Code version
    for (const u of tagText(block, 'usage').matchAll(/<(\w+)>\s*(\d+)\s*<\/\1>|^\s*(\w+)\s*:\s*(\d+)\s*$/gm)) usage[u[1] || u[3]] = Number(u[2] || u[4]);
    let result = tagText(block, 'result');
    if (result.length > RESULT_MAX) result = result.slice(0, RESULT_MAX) + '\n\n(truncated)';
    const status = tagText(block, 'status').toLowerCase();
    cards.push({
      summary: tagText(block, 'summary').slice(0, 500) || 'Background task',
      status: /^[a-z_-]{1,20}$/.test(status) ? status : 'unknown',
      durationMs: usage.duration_ms ?? null,
      tokens: usage.total_tokens ?? usage.subagent_tokens ?? null,
      toolUses: usage.tool_uses ?? null,
      result,
    });
  }
  return cards.length ? cards : null;
}

function isMetaUserText(text) {
  const t = (text || '').trim();
  return !t || META_USER_PREFIXES.some((p) => t.startsWith(p));
}

function isRealUserMessage(content) {
  if (typeof content === 'string') return content.trim().length > 0;
  if (Array.isArray(content)) {
    const hasText = content.some((p) => p?.type === 'text' && (p.text || '').trim());
    const onlyToolResults = content.length > 0 && content.every((p) => p?.type === 'tool_result');
    return hasText && !onlyToolResults;
  }
  return false;
}

function parseLine(line) {
  if (!line || !line.trim()) return null;
  let obj;
  try { obj = JSON.parse(line); } catch { return null; }
  const type = obj?.type;
  const content = obj?.message?.content;
  const ts = obj?.timestamp || obj?.ts || null;
  if (type === 'user') {
    if (!isRealUserMessage(content)) return null;
    const text = textFromContent(content).trim();
    const channel = parseChannelText(text);
    if (channel) return { role: 'user', text: channel.text, ts: channel.meta.ts || ts, meta: channel.meta };
    const tasks = text.startsWith('<task-notification>') ? parseTaskNotifications(text) : null;
    if (tasks) return tasks.map((task) => ({ role: 'task', ts, task }));
    // isMeta = injected, not typed (skill bodies, image companions); channel
    // messages carry it too, which is why they are handled first.
    if (obj.isMeta || !text || isMetaUserText(text)) return null;
    return { role: 'user', text, ts };
  }
  if (type === 'assistant') {
    const text = textFromContent(content).trim();
    if (text) return { role: 'assistant', text, tools: toolsFromContent(content), ts };
  }
  return null;
}

const INITIAL_TAIL = 50;

// Read new turns from `file` starting at BYTE offset `after`. cursor = offset
// just past the last COMPLETE line; a trailing partial line waits for the next
// read. A shrunk file (rotation) restarts from 0.
async function readTurns(file, after = 0) {
  let stat;
  try { stat = await fs.stat(file); } catch { return { turns: [], cursor: after }; }
  const start = (after > stat.size || after < 0) ? 0 : after;
  if (start >= stat.size) return { turns: [], cursor: start };
  let text;
  try {
    const fh = await fs.open(file, 'r');
    try {
      const len = stat.size - start;
      const buf = Buffer.alloc(len);
      await fh.read(buf, 0, len, start);
      text = buf.toString('utf-8');
    } finally { await fh.close(); }
  } catch { return { turns: [], cursor: after }; }
  const lastNl = text.lastIndexOf('\n');
  if (lastNl < 0) return { turns: [], cursor: start };
  const consumable = text.slice(0, lastNl + 1);
  const cursor = start + Buffer.byteLength(consumable, 'utf-8');
  const turns = [];
  for (const line of consumable.split('\n')) {
    const t = parseLine(line);
    if (Array.isArray(t)) turns.push(...t);
    else if (t) turns.push(t);
  }
  const out = (start === 0 && turns.length > INITIAL_TAIL) ? turns.slice(-INITIAL_TAIL) : turns;
  return { turns: out, cursor };
}

// The one entry point. Never throws.
export async function chatState(bot, after = 0) {
  try {
    const file = await currentTranscript(bot);
    if (!file) return { available: true, hasSession: false, turns: [], cursor: 0, file: null };
    const { turns, cursor } = await readTurns(file, after);
    return { available: true, hasSession: true, turns, cursor, file: path.basename(file).replace(/\.jsonl$/, '') };
  } catch (e) {
    return { available: false, reason: 'transcript unreadable (format is internal to Claude Code and may have changed)', hasSession: false, turns: [], cursor: after, file: null };
  }
}
