// @ts-check
// Chat view - render a bot's live Claude Code session as clean chat turns.
//
// BEST-EFFORT ONLY. This reads Claude Code's session transcript
// (<config home>/projects/<slug>/<session>.jsonl). That format is internal
// and may change between Claude Code versions; nothing else in BotCorp
// depends on this module, every entry point is wrapped, and a failure
// degrades to { available: false } so the terminal view still works. The
// compose box does not go through here: it writes keystrokes to the pty.

import { promises as fs } from 'node:fs';
import path from 'node:path';
import { ccProjectSlug } from './bots.mjs';

// Interactive sessions write "entrypoint":"cli"; a headless `claude --print`
// (a hook's timeline distill, say) writes "sdk-cli". The first entry follows
// the first prompt, which can be long, so up to 1 MB of head is read. The
// unescaped pattern cannot match inside a JSON string. An entrypoint never
// changes, so a found one is cached per file.
const entrypoints = new Map();
async function entrypointOf(file) {
  if (entrypoints.has(file)) return entrypoints.get(file);
  let fh;
  try {
    fh = await fs.open(file, 'r');
    const buf = Buffer.alloc(1 << 20);
    const { bytesRead } = await fh.read(buf, 0, buf.length, 0);
    const m = /"entrypoint":"([^"]+)"/.exec(buf.toString('utf8', 0, bytesRead));
    if (m) entrypoints.set(file, m[1]);
    return m ? m[1] : null;
  } catch { return null; } finally { await fh?.close(); }
}

// Locate the bot's ACTIVE transcript: the newest interactive .jsonl under
// projects/, preferring the dir whose slug is the bot's own BOT_HOME. Never an
// SDK (headless) run's. Not the daemon's recorded session id: a /clear starts a
// new transcript and that id stays stale until the next launch. null when there
// is none yet.
export async function currentTranscript(bot) {
  const projectsDir = path.join(bot.configDir, 'projects');
  let dirs;
  try { dirs = await fs.readdir(projectsDir, { withFileTypes: true }); } catch { return null; }
  const ownSlug = ccProjectSlug(bot.home).toLowerCase();
  const cands = [];
  for (const d of dirs) {
    if (!d.isDirectory()) continue;
    const own = d.name.toLowerCase() === ownSlug;
    const dir = path.join(projectsDir, d.name);
    let files;
    try { files = await fs.readdir(dir); } catch { continue; }
    for (const f of files) {
      if (!f.endsWith('.jsonl')) continue;
      let st;
      try { st = await fs.stat(path.join(dir, f)); } catch { continue; }
      cands.push({ file: path.join(dir, f), mtime: st.mtimeMs, own });
    }
  }
  cands.sort((a, b) => (b.own - a.own) || (b.mtime - a.mtime));
  for (const c of cands) {
    if (!(await entrypointOf(c.file) || '').startsWith('sdk')) return c.file;
  }
  return null;
}

function textFromContent(content) {
  if (typeof content === 'string') return content;
  if (Array.isArray(content)) return content.filter((p) => p?.type === 'text').map((p) => p.text || '').join('\n');
  return '';
}

function toolsFromContent(content) {
  if (!Array.isArray(content)) return [];
  return content.filter((p) => p?.type === 'tool_use').map((p) => p.name).filter(Boolean);
}

// Claude Code injects synthetic "user" entries that nobody typed: slash-command
// wrappers, their captured output, bash-mode carriers and the "Caveat:" preamble.
const META_USER_PREFIXES = [
  '<command-name>', '<command-message>', '<command-args>',
  '<local-command-stdout>', '<local-command-stderr>',
  '<bash-input>', '<bash-stdout>', '<bash-stderr>',
  '<task-notification>', '<system-reminder>',
  'Caveat: The messages below were generated by the user while running local commands',
];

// Inbound channel messages (Telegram and any other `source=`) arrive as
//   <channel source="plugin:telegram:telegram" chat_id=".." user=".." ts="..">body</channel>
// possibly several per entry, with surrounding text. Returned as body text plus
// a small meta line; each attachment becomes a labelled item
// ({kind, label, detail}), never a filesystem path or a file id.
const CHANNEL_RE = /<channel\b([^>]*)>([\s\S]*?)<\/channel>/g;
const ATTR_RE = /([a-zA-Z_][\w-]*)\s*=\s*"([^"]*)"/g;
function sourceLabel(src) {
  const last = String(src || '').split(':').filter(Boolean).pop() || '';
  return last ? last.charAt(0).toUpperCase() + last.slice(1) : 'Channel';
}
const MEDIA_LABELS = { voice: 'Voice note', audio: 'Audio', video: 'Video', video_note: 'Video note', document: 'File', sticker: 'Sticker', photo: 'Photo' };
// The body the Telegram plugin sends when an attachment has no caption: it
// only repeats what the label already says.
const PLACEHOLDER_RE = /^\((?:voice message|photo|video|video note|sticker[^)]*|document: [^)]*|audio: [^)]*)\)$/;
function fmtSize(v) {
  const n = Number(v);
  if (!Number.isFinite(n) || n <= 0) return '';
  return n < 1024 ? `${n} B` : n < 1048576 ? `${Math.round(n / 1024)} KB` : `${(n / 1048576).toFixed(1)} MB`;
}
function fmtClock(v) {
  const s = Math.round(Number(v));
  if (!Number.isFinite(s) || s < 0) return '';
  return `${Math.floor(s / 60)}:${String(s % 60).padStart(2, '0')}`;
}
function mediaItems(attrs) {
  const items = [];
  if (attrs.image_path) items.push({ kind: 'photo', label: 'Photo', detail: '' });
  if (attrs.attachment_file_id || attrs.attachment_name || attrs.attachment_kind) {
    const kind = Object.hasOwn(MEDIA_LABELS, attrs.attachment_kind || '') ? attrs.attachment_kind : 'document';
    const name = attrs.attachment_name ? String(attrs.attachment_name).replace(/^.*[\\/]/, '').slice(0, 80) : '';
    const dur = fmtClock(attrs.attachment_duration ?? attrs.duration);
    const parts = kind === 'voice' || kind === 'video_note' ? [dur]
      : kind === 'audio' || kind === 'video' ? [name, dur]
      : kind === 'sticker' ? []
      : [name, fmtSize(attrs.attachment_size)];
    items.push({ kind, label: MEDIA_LABELS[kind], detail: parts.filter(Boolean).join(' · ') });
  }
  return items;
}
export function parseChannelText(text) {
  const blocks = [];
  let rest = '';
  let at = 0;
  for (const m of String(text || '').matchAll(CHANNEL_RE)) {
    rest += text.slice(at, m.index);
    at = m.index + m[0].length;
    const attrs = {};
    for (const a of m[1].matchAll(ATTR_RE)) attrs[a[1]] = a[2];
    const media = mediaItems(attrs);
    let body = m[2].trim();
    if (media.length && PLACEHOLDER_RE.test(body)) body = '';
    blocks.push({ body, source: sourceLabel(attrs.source), telegram: /telegram/i.test(attrs.source || ''), user: attrs.user || null, ts: attrs.ts || null, media });
  }
  if (!blocks.length) return null;
  // a reminder the harness wrapped around the message is not what anyone sent
  rest = (rest + text.slice(at)).replace(/<system-reminder>[\s\S]*?<\/system-reminder>/g, '').trim();
  const first = blocks[0];
  const body = [rest, ...blocks.map((b) => b.body)].filter(Boolean).join('\n\n');
  return { text: body, meta: { source: first.source, channel: first.telegram ? 'telegram' : null, user: first.user, ts: first.ts, media: blocks.flatMap((b) => b.media) } };
}
// Background agents and commands report back as a synthetic user entry:
//   <task-notification><task-id>..</task-id><output-file>..</output-file>
//   <status>completed</status><summary>..</summary><result>..</result>
//   <usage><total_tokens>N</total_tokens><tool_uses>N</tool_uses><duration_ms>N</duration_ms></usage>
// A system event, not something anyone typed: one card per block, carrying only
// summary, status, usage and result (never the output-file path or ids).
const TASK_RE = /<task-notification>([\s\S]*?)<\/task-notification>/g;
const RESULT_MAX = 20000;
function tagText(block, name) {
  const open = block.indexOf(`<${name}>`);
  if (open < 0) return '';
  const from = open + name.length + 2;
  // the result is free text that may quote a closing tag: take the last one
  const close = name === 'result' ? block.lastIndexOf(`</${name}>`) : block.indexOf(`</${name}>`, from);
  return close < from ? '' : block.slice(from, close).trim();
}
export function parseTaskNotifications(text) {
  const cards = [];
  for (const m of String(text || '').matchAll(TASK_RE)) {
    const block = m[1];
    const usage = {};
    // <usage> is child tags or `key: value` lines, depending on the Claude Code version
    for (const u of tagText(block, 'usage').matchAll(/<(\w+)>\s*(\d+)\s*<\/\1>|^\s*(\w+)\s*:\s*(\d+)\s*$/gm)) usage[u[1] || u[3]] = Number(u[2] || u[4]);
    let result = tagText(block, 'result');
    if (result.length > RESULT_MAX) result = result.slice(0, RESULT_MAX) + '\n\n(truncated)';
    const status = tagText(block, 'status').toLowerCase();
    cards.push({
      summary: tagText(block, 'summary').slice(0, 500) || 'Background task',
      status: /^[a-z_-]{1,20}$/.test(status) ? status : 'unknown',
      durationMs: usage.duration_ms ?? null,
      tokens: usage.total_tokens ?? usage.subagent_tokens ?? null,
      toolUses: usage.tool_uses ?? null,
      result,
    });
  }
  return cards.length ? cards : null;
}

function isMetaUserText(text) {
  const t = (text || '').trim();
  return !t || META_USER_PREFIXES.some((p) => t.startsWith(p));
}

function isRealUserMessage(content) {
  if (typeof content === 'string') return content.trim().length > 0;
  if (Array.isArray(content)) {
    const hasText = content.some((p) => p?.type === 'text' && (p.text || '').trim());
    const onlyToolResults = content.length > 0 && content.every((p) => p?.type === 'tool_result');
    return hasText && !onlyToolResults;
  }
  return false;
}

// Voice notes: the bot transcribes one by running the harness transcriber
// (tools/tg/transcribe.py) through Bash, and that tool result IS the
// transcript. The call's id is remembered so its result, in a later entry, can
// be passed on as a `transcript` turn; nothing is transcribed here.
const TRANSCRIBE_RE = /\btranscribe\.py\b/;
const TRANSCRIPT_MAX = 4000;
const transcribeIds = new Set();
function noteTranscribeCalls(content) {
  if (!Array.isArray(content)) return;
  for (const p of content) {
    if (p?.type !== 'tool_use' || p.name !== 'Bash' || !p.id || !TRANSCRIBE_RE.test(String(p.input?.command || ''))) continue;
    transcribeIds.add(p.id);
    if (transcribeIds.size > 200) transcribeIds.delete(transcribeIds.values().next().value);
  }
}
function transcriptFrom(content) {
  if (!Array.isArray(content)) return null;
  for (const p of content) {
    if (p?.type !== 'tool_result' || !transcribeIds.has(p.tool_use_id)) continue;
    transcribeIds.delete(p.tool_use_id);
    if (p.is_error) return null;
    // the transcriber's one stderr line ("[transcribe] groq ...") is not speech
    const text = textFromContent(p.content).split('\n').filter((l) => !l.startsWith('[transcribe]')).join('\n').trim();
    return text ? text.slice(0, TRANSCRIPT_MAX) : null;
  }
  return null;
}

// Telegram replies the bot sends, both ways it sends them: the channel plugin's
// reply tool (mcp__plugin_telegram_telegram__reply {chat_id, text, reply_to})
// and the harness sender run through Bash (`python tools/tg/tg_send.py [flags]
// "text"`, or the text as a heredoc). Each becomes a `tg_out` turn carrying the
// sent text only, never the chat id. Read at the call: a send the gate refused
// still shows, as the call it was.
const TG_REPLY_TOOL_RE = /^mcp__plugin_telegram[\w-]*__reply$/;
const TG_SEND_RE = /\btg_send\.py\b/g;
const TG_VALUE_FLAGS = new Set(['--chat-id', '--reply-to', '--photo']);
const TG_NO_SEND = new Set(['--answered', '--unanswered', '--check', '--alert']);
const TG_TEXT_MAX = 8000;
// The words of one shell command after tg_send.py, up to the first unquoted
// ; | & < > or newline; null when a word is a command substitution (unknown text).
function shellWords(s) {
  const words = [];
  /** @type {string | null} */
  let cur = null;
  let i = 0;
  const push = () => { if (cur !== null) words.push(cur); cur = null; };
  while (i < s.length) {
    const c = s[i];
    if (c === "'") {
      const j = s.indexOf("'", i + 1);
      if (j < 0) return null;
      cur = (cur ?? '') + s.slice(i + 1, j);
      i = j + 1;
    } else if (c === '"') {
      let v = '', j = i + 1;
      for (; j < s.length && s[j] !== '"'; j++) {
        if (s[j] === '\\' && '"\\$`'.includes(s[j + 1])) v += s[++j];
        else if ((s[j] === '$' && s[j + 1] === '(') || s[j] === '`') return null;
        else v += s[j];
      }
      if (j >= s.length) return null;
      cur = (cur ?? '') + v;
      i = j + 1;
    } else if (/[;|&<>\n)]/.test(c)) {
      if (cur !== null && /^\d$/.test(cur) && (c === '>' || c === '<')) cur = null;   // 2>&1
      break;
    } else if (/\s/.test(c)) { push(); i++; }
    else if (c === '\\' && i + 1 < s.length) { cur = (cur ?? '') + s[i + 1]; i += 2; }
    else { cur = (cur ?? '') + c; i++; }
  }
  push();
  return words;
}
export function tgSendTexts(command) {
  const cmd = String(command || '');
  const out = [];
  for (const m of cmd.matchAll(TG_SEND_RE)) {
    const rest = cmd.slice(m.index + m[0].length);
    // the text as a heredoc: "$(cat <<'EOF' ... EOF)" as an argument, or on stdin
    const sub = /^[^\n]*?"\$\(cat <<-?'?(\w+)'?\n([\s\S]*?)\n\s*\1\s*\n?\)"/.exec(rest);
    const stdin = sub ? null : /^([^\n|;&]*?)<<-?'?(\w+)'?\n([\s\S]*?)\n\2(?:\n|$)/.exec(rest);
    const words = shellWords(sub ? rest.slice(0, rest.indexOf('"$(cat')) : stdin ? stdin[1] : rest);
    if (!words) continue;
    let text = sub ? sub[2] : stdin ? stdin[3] : null, replyTo = null, skip = false;
    for (let k = 0; k < words.length; k++) {
      const [w, eq] = words[k].split(/=(.*)/s);
      if (TG_NO_SEND.has(w)) skip = true;
      else if (TG_VALUE_FLAGS.has(w)) { const v = eq ?? words[++k]; if (w === '--reply-to') replyTo = v || null; }
      else if (!w.startsWith('-') && text === null) text = words[k];
    }
    if (!skip && text && text.trim()) out.push({ text: text.trim().slice(0, TG_TEXT_MAX), replyTo });
  }
  return out;
}
function tgSends(content, ts) {
  if (!Array.isArray(content)) return [];
  const turns = [];
  for (const p of content) {
    if (p?.type !== 'tool_use') continue;
    if (TG_REPLY_TOOL_RE.test(String(p.name || '')) && typeof p.input?.text === 'string' && p.input.text.trim()) {
      turns.push({ role: 'tg_out', text: p.input.text.trim().slice(0, TG_TEXT_MAX), replyTo: p.input.reply_to != null ? String(p.input.reply_to) : null, ts });
    } else if (p.name === 'Bash') {
      for (const s of tgSendTexts(p.input?.command)) turns.push({ role: 'tg_out', ...s, ts });
    }
  }
  return turns;
}

function parseLine(line) {
  if (!line || !line.trim()) return null;
  let obj;
  try { obj = JSON.parse(line); } catch { return null; }
  const type = obj?.type;
  const content = obj?.message?.content;
  const ts = obj?.timestamp || obj?.ts || null;
  if (type === 'user') {
    const transcript = transcriptFrom(content);
    if (transcript) return { role: 'transcript', text: transcript, ts };
    if (!isRealUserMessage(content)) return null;
    const text = textFromContent(content).trim();
    const channel = parseChannelText(text);
    if (channel) return channel.text || channel.meta.media.length ? { role: 'user', text: channel.text, ts: channel.meta.ts || ts, meta: channel.meta } : null;
    const tasks = text.startsWith('<task-notification>') ? parseTaskNotifications(text) : null;
    if (tasks) return tasks.map((task) => ({ role: 'task', ts, task }));
    // isMeta = injected, not typed (skill bodies, image companions); channel
    // messages carry it too, which is why they are handled first.
    if (obj.isMeta || !text || isMetaUserText(text)) return null;
    return { role: 'user', text, ts };
  }
  if (type === 'assistant') {
    noteTranscribeCalls(content);
    const text = textFromContent(content).trim();
    const sent = tgSends(content, ts);
    if (text) return sent.length ? [{ role: 'assistant', text, tools: toolsFromContent(content), ts }, ...sent] : { role: 'assistant', text, tools: toolsFromContent(content), ts };
    if (sent.length) return sent;
  }
  return null;
}

const INITIAL_TAIL = 50;

// Read new turns from `file` starting at BYTE offset `after`. cursor = offset
// just past the last COMPLETE line; a trailing partial line waits for the next
// read. A shrunk file (rotation) restarts from 0.
export async function readTurns(file, after = 0) {
  let stat;
  try { stat = await fs.stat(file); } catch { return { turns: [], cursor: after }; }
  const start = (after > stat.size || after < 0) ? 0 : after;
  if (start >= stat.size) return { turns: [], cursor: start };
  let text;
  try {
    const fh = await fs.open(file, 'r');
    try {
      const len = stat.size - start;
      const buf = Buffer.alloc(len);
      await fh.read(buf, 0, len, start);
      text = buf.toString('utf-8');
    } finally { await fh.close(); }
  } catch { return { turns: [], cursor: after }; }
  const lastNl = text.lastIndexOf('\n');
  if (lastNl < 0) return { turns: [], cursor: start };
  const consumable = text.slice(0, lastNl + 1);
  const cursor = start + Buffer.byteLength(consumable, 'utf-8');
  const turns = [];
  for (const line of consumable.split('\n')) {
    const t = parseLine(line);
    if (Array.isArray(t)) turns.push(...t);
    else if (t) turns.push(t);
  }
  const out = (start === 0 && turns.length > INITIAL_TAIL) ? turns.slice(-INITIAL_TAIL) : turns;
  return { turns: out, cursor };
}

// The one entry point. Never throws.
export async function chatState(bot, after = 0) {
  try {
    const file = await currentTranscript(bot);
    if (!file) return { available: true, hasSession: false, turns: [], cursor: 0, file: null };
    const { turns, cursor } = await readTurns(file, after);
    return { available: true, hasSession: true, turns, cursor, file: path.basename(file).replace(/\.jsonl$/, '') };
  } catch (e) {
    return { available: false, reason: 'transcript unreadable (format is internal to Claude Code and may have changed)', hasSession: false, turns: [], cursor: after, file: null };
  }
}
