// Every user-facing string of the cockpit, grouped by the role it plays. The
// group is the word cap (IA §6); copy.test.ts checks every string against its
// cap and the banned terms. `{name}` slots are filled with t().
//
// Labels and icons first: no intro paragraphs, status is one coloured word.

export const COPY = {
  // nav and tab labels: 1 word
  nav: {
    bots: 'Bots',
    inbox: 'Inbox',
    accounts: 'Accounts',
    settings: 'Settings',
  },
  // a bot's tabs and views: 1 word
  tab: {
    settings: 'Settings',
    telegram: 'Telegram',
    secrets: 'Secrets',
    automations: 'Automations',
    tools: 'Tools',
    knowledge: 'Knowledge',
    chat: 'Chat',
    terminal: 'Terminal',
  },
  // screen and sheet titles: 2 words
  title: {
    history: 'Session history',
    newChat: 'New chat',
    newBot: 'New bot',
    bots: 'Bots',
    inbox: 'Inbox',
    accounts: 'Accounts',
    settings: 'Settings',
    updates: 'Updates',
    addAccount: 'Add account',
    pairBrowser: 'Pair browser',
    help: 'Help',
    knowledge: 'Knowledge',
    newDoc: 'New doc',
  },
  // buttons: 3 words, verb first
  button: {
    newChat: 'New chat',
    newBot: 'New bot',
    showAll: 'Show all {n}',
    showFewer: 'Show fewer',
    update: 'Update',
    open: 'Open',
    cancel: 'Cancel',
    back: 'Back',
    botMenu: 'Bot menu',
    start: 'Start',
    startAgain: 'Start again',
    restart: 'Restart',
    restartFresh: 'Restart fresh',
    stop: 'Stop',
    stopArchive: 'Stop and archive',
    history: 'Session history',
    send: 'Send',
    attach: 'Attach a file',
    removeFile: 'Remove {file}',
    jumpLatest: 'Jump to latest',
    dismiss: 'Dismiss',
    result: 'Result',
    startChat: 'Start chat',
    createBot: 'Create bot',
    save: 'Save',
    saveBackups: 'Save backups',
    pair: 'Pair',
    deny: 'Deny',
    replace: 'Replace',
    add: 'Add',
    addSecret: 'Add secret',
    unlock: 'Unlock',
    runNow: 'Run now',
    pause: 'Pause',
    resume: 'Resume',
    register: 'Register',
    removeEntry: 'Remove entry',
    retire: 'Retire',
    scan: 'Scan',
    approve: 'Approve',
    decline: 'Decline',
    link: 'Link',
    openTab: 'Open',
    addAccount: 'Add account',
    rename: 'Rename',
    removeAccount: 'Remove account',
    apply: 'Apply {tag}',
    skip: 'Skip',
    rollback: 'Roll back',
    cancelRequest: 'Cancel request',
    revoke: 'Revoke',
    edit: 'Edit',
    preview: 'Preview',
    newDoc: 'New doc',
    deleteDoc: 'Delete doc',
    editIn: 'Edit in Settings',
    editDescription: 'Edit {name}',
    createDoc: 'Create doc',
  },
  // row labels, section names, landmark and control names: 3 words
  row: {
    brand: 'BotCorp',
    pinned: 'Pinned',
    chats: 'Chats',
    cockpitNav: 'cockpit',
    telegramOn: 'Telegram on',
    waiting: '{n} waiting',
    version: 'BotCorp {version}',
    context: 'Context',
    contextHint: 'What is Context?',
    account: 'Account',
    transcript: 'Transcript',
    sentOnTelegram: 'Sent on Telegram',
    message: 'Message {bot}',
    view: 'View',
    keys: 'Terminal keys',
    conversation: 'Conversation',
    tokens: '{n} tokens',
    toolUses: '{n} tools',
    file: 'File',
    task: 'Task',
    name: 'Name',
    persona: 'Persona',
    telegram: 'Telegram',
    telegramToken: 'Telegram token',
    keepRunning: 'Keep running',
    nameRule: 'Lowercase, digits, hyphens',
    // a bot's manage tabs
    model: 'Model',
    chain: 'Account chain',
    backups: 'Backups',
    backupsHint: 'What are Backups?',
    tellMe: 'Notify on Telegram',
    reviewBoard: 'Answer page',
    taskBoard: 'Task board',
    projectLink: 'GitHub project link',
    projectRule: 'Invalid project link',
    advanced: 'Advanced',
    adminBot: 'Admin bot',
    adminHint: 'Admin bot help',
    autoFix: 'Auto-fix alerts',
    debrief: 'Session debrief',
    hubUrl: 'Status hub URL',
    backupRepo: 'Backup repo',
    sound: 'Sound',
    diagnostics: 'Diagnostics',
    folder: 'Folder',
    whoCanMessage: 'Who can message',
    paired: 'Paired',
    onlyListed: 'Only listed',
    nobody: 'Nobody',
    waitingToPair: 'Waiting to pair',
    allowedSenders: 'Allowed senders',
    secretName: 'Secret name',
    secretValue: 'Value',
    lockPass: 'Lock with passphrase',
    lockHint: 'Passphrase lock help',
    passphrase: 'Passphrase',
    recentRuns: 'Recent runs',
    searchTools: 'Search tools',
    filter: 'Show',
    all: 'All',
    harness: 'Harness',
    own: 'Own',
    thirdParty: 'Third-party',
    position: 'Position {n}',
    primaryTag: 'Primary',
    backupTag: 'Backup',
    moveUp: 'Move {name} up',
    moveDown: 'Move {name} down',
    removeFrom: 'Remove {name}',
    addBackup: 'Add a backup',
    registry: 'Registry',
    unregistered: 'Unregistered',
    missing: 'Missing',
    replaceValue: 'New {key} value',
    bot: 'Bot',
    // accounts
    fiveHour: '5 h',
    sevenDay: '7 d',
    usedBy: 'Used by',
    primary: 'primary',
    backupN: 'backup {n}',
    label: 'Label',
    setupToken: 'Setup token',
    setupHint: 'Setup token help',
    resets: 'resets {time}',
    noReading: 'n/a',
    accountMenu: 'Menu for {name}',
    // updates
    installed: 'Installed',
    newer: 'Newer',
    history: 'History',
    releaseNotes: 'Release notes',
    engine: 'Engine',
    engineName: 'Claude Code',
    // settings
    appearance: 'Appearance',
    auto: 'Auto',
    light: 'Light',
    dark: 'Dark',
    copySelect: 'Copy on select',
    pairedBrowsers: 'Paired browsers',
    help: 'Help',
    guide: 'How BotCorp works',
    thisBrowser: 'This browser',
    pairingCode: 'Enter pairing code',
    unknownBrowser: 'A browser',
    // model, effort, ultracode
    effort: 'Effort',
    tierDefault: 'Tier default',
    ultracode: 'Ultracode',
    tiers: 'Tiers',
    liveModels: 'Claude Code {version}',
    // the background helpers' facts
    everyMin: 'Every {n} min',
    everyHours: 'Every {n} h',
    writesTo: 'Writes {file}',
    lastRun: 'Last run {ago}',
    notRunYet: 'Not run yet',
    // knowledge
    allBots: 'All bots',
    thisBot: 'This bot',
    docName: 'Doc name',
    docRule: 'Lowercase, digits, hyphens',
    tokensEst: '~{n} tokens',
    edited: 'edited {ago}',
    docText: 'Doc text',
    total: 'Total',
    // descriptions
    description: 'Description',
    // an approval, explained
    who: 'Who',
    change: 'Change',
    why: 'Why',
    onApprove: 'Approve →',
    onDecline: 'Decline →',
    when: 'When',
    exactChange: 'Exact change',
    // subagents
    subagents: 'Subagents',
    recentAgents: 'Last 10 finished',
    agentOf: '{bot} subagent',
  },
  // status words: 4 words
  status: {
    waiting: 'Waiting · Approve',
    signIn: 'Sign-in needed',
    accOk: 'ok',
    accLimited: 'limited until {time}',
    accFailed: 'failed',
    accNoToken: 'no token',
    comesWith: 'comes with {tag}',
    appliesAtPause: 'applies at next pause',
    failed: 'failed',
    skipped: 'skipped',
    upToDate: 'Up to date',
    ended: 'Session ended',
    unavailable: 'Chat unavailable',
    newSession: 'New session',
    uploading: 'uploading',
    notRunning: 'Not running',
    noTerminal: 'No terminal attached',
    locked: 'Locked',
    unlocked: 'Unlocked',
    off: 'Off',
    paused: 'Paused',
    alwaysOn: 'Always on',
    missing: 'Missing on disk',
    restartToApply: 'Restart to apply',
    nothingFeeds: 'Nothing feeds it',
    loadsNextStart: 'Loads at next start',
    readOnlyHere: 'Read-only here',
    running: 'Running',
    done: 'Done',
    doneMaybe: 'Probably done',
    tooBig: 'Over 20k tokens',
  },
  // empty states: 4 words
  empty: {
    noBots: 'No bots yet',
    noChats: 'No chats yet',
    pickBot: 'Pick a bot',
    nothingYet: 'Nothing here yet',
    noConversation: 'No conversation yet',
    noSessions: 'No sessions yet',
    noBot: 'No such bot',
    noAccounts: 'No accounts yet',
    noUsage: 'No usage yet',
    noBrowsers: 'No browsers paired',
    noAutomations: 'No automations',
    noSecrets: 'No secrets yet',
    noToolMatch: 'No tool matches',
    noToolList: 'No tool list',
    nobodyWaiting: 'Nobody waiting',
    nothingToRegister: 'Nothing to register',
    noDocs: 'No docs yet',
    noAgents: 'No subagents running',
    noAgent: 'No such subagent',
    pickDoc: 'Pick a doc',
  },
  // toasts: 6 words
  toast: {
    appliesOnRestart: 'Applies on restart',
    starting: 'Starting {bot}',
    restarting: 'Restarting {bot}',
    stopping: 'Stopping {bot}',
    archived: '{bot} archived',
    attached: 'Attached. Add your message.',
    saved: 'Saved',
    waitingApproval: 'Waiting for your approval',
    secretSaved: '{key} saved',
    paired: 'Paired',
    denied: 'Denied',
    unlocked: 'Vault unlocked',
    ran: '{name} queued',
    registered: '{tool} registered',
    retired: '{tool} retired',
    chainSaved: 'Backups saved',
    found: '{n} found',
    approved: 'Approved',
    declined: 'Declined',
    linked: 'Accounts linked',
    accountAdded: '{name} added',
    renamed: 'Renamed',
    accountRemoved: '{name} removed',
    applying: 'Applying {tag}',
    rollingBack: 'Rolling back to {tag}',
    skippedTag: 'Skipped {tag}',
    requestCancelled: 'Request cancelled',
    browserPaired: 'Browser paired',
    browserRevoked: 'Browser revoked',
    docSaved: '{doc} saved',
    docDeleted: '{doc} deleted',
    docConflict: 'Changed elsewhere. Reloaded it.',
  },
  // Inbox items and the attention banner: 12 words
  inbox: {
    banner: '{n} things need you',
    bannerOne: '1 thing needs you',
    decided: 'Decided',
    adminDone: 'Done by an admin bot',
    approved: 'approved by {who}',
    rejected: 'declined by {who}',
    refused: 'refused',
    nothing: 'Nothing needs you',
    declineReason: 'Reason (optional)',
    tellWhy: 'Tell the bot why',
    keepOpen: 'Keep it open',
    linkLine: 'Puts each bot on its own named account.',
    adminBot: '{bot} (admin bot)',
  },
  // what kind of thing an Inbox item is: 4 words
  kind: {
    approval: 'Approval',
    pairing: 'Pairing',
    vault_locked: 'Vault locked',
    blocked: 'Waiting on you',
    down: 'Down',
    automation_failing: 'Job failing',
    registry: 'Tool list',
    usage_blocked: 'Limit reached',
    account: 'Account',
    account_unlinked: 'Link accounts',
    release: 'Update',
    cc_rejected: 'Engine update held back',
  },
  // what a harness module does, shown in the Tools tab: 10 words
  module: {
    telegram: 'Reads and answers its Telegram chat.',
    board: 'Works from your GitHub project board.',
    alert_triage: 'Fixes what its monitors find, or files a card.',
    hub: 'Sends its status to your hub.',
    debrief: 'Writes a short debrief when a session ends.',
    auto_commit: 'Saves its folder to git after each turn.',
    memory_sync: 'Backs up its memory to its own repo.',
    sound: 'Plays a sound when it finishes.',
    review_board: 'Keeps one answer page for your decisions.',
  },
  // the ? tooltips: 20 words, and only on the five complex things (§6)
  tooltip: {
    backups: 'Used in order when a limit hits. Position 1 is the primary.',
    setupToken: 'In a terminal signed in to this account, run `claude setup-token`. Paste the result.',
    admin: 'An admin bot may run operator-only commands. Every one is logged, and changes still wait for you.',
    lock: 'The vault opens only after you enter the passphrase, once per start.',
    context: 'The share of the window used before the chat is compacted.',
    autoFix: "Starts a background run to fix new alerts or file a card. No Telegram unless critical; uses your plan's limit.",
    debrief: "After a session, a background run notes it in the session log. No Telegram; uses your plan's limit.",
  },
  // confirms (§7): a title of 5 words, a consequence of 10, a verb button of 3
  confirm: {
    restart: { title: 'Restart {bot}?', body: 'Keeps the conversation.', verb: 'Restart {bot}' },
    fresh: { title: 'Restart {bot} fresh?', body: 'Starts a new conversation.', verb: 'Restart fresh' },
    stop: { title: 'Stop {bot}?', body: 'Telegram stops until you start it.', verb: 'Stop {bot}' },
    stopArchive: { title: 'Stop and archive {bot}?', body: 'Stops it and leaves the list.', verb: 'Stop and archive' },
    telegram: { title: 'Change Telegram?', body: 'A wrong setting can cut it off.', verb: 'Change Telegram' },
    pairSender: { title: 'Pair this sender?', body: 'They can message the bot.', verb: 'Pair sender' },
    removeAccount: { title: 'Remove {account}?', body: 'Its token leaves the vault.', verb: 'Remove account' },
    chain: { title: "Save {bot}'s backups?", body: 'Used in order when a limit hits.', verb: 'Save backups' },
    primary: { title: 'Switch {bot} to {account}?', body: 'Keeps the conversation.', verb: 'Switch account' },
    apply: { title: 'Apply {tag}?', body: 'Bots switch at their next pause.', verb: 'Apply {tag}' },
    rollback: { title: 'Roll back to {tag}?', body: 'Bots switch at their next pause.', verb: 'Roll back' },
    retire: { title: 'Retire {tool}?', body: 'Files move to the retired folder.', verb: 'Retire tool' },
    replaceSecret: { title: 'Replace {key}?', body: 'The old value is gone.', verb: 'Replace secret' },
    revoke: { title: 'Revoke this browser?', body: 'It must pair again.', verb: 'Revoke' },
    link: { title: 'Link accounts?', body: 'Bots switch to their account at next start.', verb: 'Link accounts' },
    ultracode: { title: 'Turn on Ultracode?', body: 'Workflows on every task. Uses much more of the limit.', verb: 'Turn on' },
    deleteDoc: { title: 'Delete {doc}?', body: 'It stops loading at the next start.', verb: 'Delete doc' },
  },
} as const;

/** Fill `{slot}`s: t('Show all {n}', { n: 12 }). A missing slot stays visible. */
export function t(s: string, vars: Record<string, string | number> = {}): string {
  return s.replace(/\{(\w+)\}/g, (m, k: string) => (k in vars ? String(vars[k]) : m));
}
